### PR TITLE
Joke about not finding an opinion to give

### PR DESCRIPTION
**Pull request by katrinleinweber**
See https://github.com/ropensci/codemetar/issues/170#issuecomment-398729324.

### CODE REVIEW

**Comment by maelle** [comment]
I 💙 this! :joy:

**Comment by katrinleinweber** [comment]
The message has to be _moved_ there, right? I just tested offline, whether I broke any tests, but didn't check in higher-order functions if the `NULL` was needed.

**Comment by maelle** [comment]
You could let the function output a message instead of NULL but then is.null should be replace by == message I think? Not sure I had added a test for this actually.

**Comment by maelle** [comment]
@katrinleinweber any question? :-)

**Comment by katrinleinweber** [comment]
I don't find a way to check `== message`. They don't seem to have a type, nor a class:

```
> typeof(message("test"))
test
[1] "NULL"

```

And whenever I go for `return("...")` in `give_opinions()` plus `else if(is.character(opinions)) message(paste0(opinions))` in `create_codemeta()`, I still get `NULL` after `Install and restart` in the codemetar project with my modifications and then run `codemetar::give_opinions()` in my own project.

Am I doing the testing wrong or am I not finding the rights spots to implement the modifications?

**Comment by katrinleinweber** [comment]
If you know how to implement this, please feel free to do it. I fiddled around with this for about 30min last time, and for 1h now. 30min more would be OK, but I also enabled `edits from maintainer` ;-)

**Comment by maelle** [comment]
Implemented by a message before returning `NULL`.

**Comment by katrinleinweber** [comment]
Ah, that's how: 5465b3f13affc12f356f2c2fce568612c3f870fd. Thanks :-)

**Comment by maelle** [comment]
Easy lazy fix :-D

**Pull request closed without merging**
