### PR TITLE
Work for v0.1.6

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
@cboettig is the vignette D too fragile for CRAN? Cf https://travis-ci.org/ropensci/codemetar/jobs/374436693#L1191

**Comment by cboettig** [comment]
@maelle quite possibly.  (Do you mean Vignette "C"?) I'm thinking the current stack of vignettes really isn't the best intro for codemetar at this point anyway?  

The intro is fine but doesn't mention the newer features (and probably needs a cleaner display).  The others are somewhat of a tangent on JSON-LD for the most part, and maybe should be moved to `inst/notebook` until we get something more focused?  (I'm planning to update the codemeta website to something a little better soon too)

**Comment by maelle** [comment]
Yes vignette c that made Travis fail.

You could move the vignettes as articles this way they would be in the pkgdown website at least?

**Comment by cboettig** [comment]
@maelle that's an option now?  Does pkgdown automatically detect things in an `articles` directory?  (I get out of date so quickly on these things!)

**Comment by maelle** [comment]
Check out usethis repo the setup article is not a vignette IIRC

**Comment by cboettig** [comment]
Ah, it's in [vignettes/articles](https://github.com/r-lib/usethis/tree/master/vignettes/articles) but it looks like that means that CHECK doesn't build it.  Very clever.

**Pull request merged**
