### PR TITLE
Add try() and pass Github token to gh::gh() (related to #175)

### PR DESCRIPTION
**Pull request by mrustl**
The changes done are related to #175.

As I frequently hit Github`s API limit for my [use case](https://kwb-r.github.io/pkgmeta/dev/articles/package-dependencies.html#with-r-package-codemetar) I passed the Github token as additional argument to gh::gh() for issues/topics/readme and also added the missing try() as requested by @maelle for the issue/topic parts.

Finally I updated the package documentation with pkgdown.

### CODE REVIEW

**Comment by cboettig** [comment]
LGTM.  @maelle I'll let you look over and merge this.

@maelle Unrelated but we could also consider relaxing our codecov targets so that they don't throw failed checks for small decreases in total test coverage like this... (I just learned how to do this over in RNeXML, check out the codecov.yml there)

**Comment by maelle** [comment]
@mrustl thanks! We haven't updated our contributing guidelines but the active branch is actually dev, could you PR to dev?

**Comment by maelle** [comment]
Also note that one can also save the token as an environment variable called `GITHUB_PAT` in which case `gh` will use it. :-)

**Comment by mrustl** [comment]
@maelle done!

**Comment by mrustl** [comment]
Sorry that I didn't get it that the changes I made were already in the dev branch. As you pointed out that 'GITHUB_TOKEN' can be used I not make any changes passing an additional 'auth_token' argument and close this pull request.

**Comment by maelle** [comment]
Ok! Sorry, will update the contributing guidelines, it was bad practice on my part.

You can still open a new PR to pass the argument if you wish. :-)

Thanks again, and thanks for reporting your use case!

**Pull request closed without merging**
