### PR TITLE
Parsing meta$ tags on CITATION

### LINKED ISSUE #321: Wrong parsing of meta$ tags on CITATION
See https://github.com/cboettig/codemeta/issues/7 and PR https://github.com/cboettig/codemeta/pull/9

The current implementation on {codemetar} fails to read some CITATION files. This is due to the `meta`  parameter used here:

https://github.com/ropensci/codemetar/blob/adc7868453c31c3868e21295f8c88f5e4e3ad169/R/parse_citation.R#L158-L165

So only the "Encoding" is used. on `utils::readCitationFile(citation_file, meta = meta)`.

 In some other CITATION files the use of `meta$` tags cab be quite extensive, see CITATION of {rmarkdown} where authors, year and title makes use ot the `meta$` approach. These tags are not found since they haven't been provided on the `meta` parameter. See {rmarkdown}:

https://github.com/rstudio/rmarkdown/blob/eaf6efc3fe6d39373ae0cee7ce3a034119bb47f5/inst/CITATION#L3-L19

When parsing directly the package it is fine, as you use `citation(pkg)` that already takes care of this, but on in-development packages the `meta` information should be extracted from DESCRIPTION.

cc: @cboettig @dpprdan @maelle

### PR DESCRIPTION
**Pull request by dieghernan**
Closes #321 

I included unit tests for all the modifications. Some other improvements:

- Actions: Adapted to the latest versions on https://github.com/r-lib/actions/tree/master/.github/workflows
- When a codemeta.json file is generated, "description" appears as a single line (on DESCRIPTION it has \n lines, I found this a bit annoying) 😄 .
- DESCRIPTION:
  - Roxygen updated to the latest version. This changed a "man" file.
  - Bump version
  - Cleaned with `usethis::use_tidy_description()`.
  - {codecov} not suggested, I added a GH action for that.
  - `read_citation_with_encoding()` is not needed any more after the PR. I removed this and updated the tests.
- I added additional `skip_` on the tests. This should fix the CRAN issue that removed the package 👍🏻 .

### CODE REVIEW

**Comment by maelle** [comment]
Thanks @dieghernan!

@cboettig will codemetar eventually call codemeta?

**Comment by cboettig** [comment]
@maelle yes that still needs to be done!

**Comment by dpprdan** [comment]
@dieghernan FYI regarding `clean_str()`: [{desc} 1.4.0 NEWS](https://github.com/r-lib/desc/blob/master/NEWS.md#breaking-change) and the corresponding [commit](https://github.com/r-lib/desc/commit/728f85ec66a65850fb145a93b775c5c0f223adde)

> `desc_get_field()` gains a boolean `squish_ws` parameter to normalize whitespace within the retrieved value.

**Comment by maelle** [comment]
@cboettig

**Pull request merged**
