### PR TITLE
I151 use GitHub topics as keywords

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
Appveyor build fail is very annoying but it's a false positive, many packages would apparently need to be reinstalled.

**Comment by katrinleinweber** [comment]
Hello! Do I understand correctly, that this code combines the GitHub Topics and the manually specified `X-schema.org-keywords` as the `keywords` list in `codemeta.json`?

I was initially thinking, that codemetar can copy the repo's topics into the `DESCRIPTION`'s `X-schema.org-keywords` list, but that's not the case, is it?

**Comment by maelle** [comment]
Yes keywords are not copied in DESCRIPTION, because the only reason to keep keywords in DESCRIPTION was to add them to codemeta.json, there's no other use cases for them that I know of? What do you think? Happy to hear any suggestions!

I find that adding keywords as repo topics is more natural, and I'd be glad to add whatever the equivalent is on other platforms (Gitlab &co)

**Comment by katrinleinweber** [comment]
I totally agree, was just confirming this piece of info before I accidentally teach codemetar's approach to schema.org the wrong way around ;-)

**Comment by maelle** [comment]
Thanks for starting the discussion!

Currently I'd actually advise to store no keyword in DESCRIPTION when the repo is on GitHub. I was imagining that one could re-populate the place for topics on another platform (say Gitlab after a migration) from `codemeta.json`? 

Cc @cboettig

**Comment by katrinleinweber** [comment]
Hm, but most of ROpenSci's packages seem to contain `X-schema.org-keywords`. Are those added manually? I followed the trail to https://github.com/ropensci/codemetar/pull/32.

**Comment by maelle** [comment]
Most? I think only @cboettig and @sckott do that, they started doing that before I implemented the repo topic ingestion I think? Or they prefer the DESCRIPTION approach maybe 😉

**Comment by katrinleinweber** [comment]
There are "tags" under a project's `Settings` > `General`, see https://gitlab.com/gitlab-org/gitlab-ce/issues/2978.

**Comment by maelle** [comment]
You mean auto-generating GitHub repo topics? No they can't but GitHub gives you suggestions. The way I've added topics to repos was using what _I_ identified as keywords, and what other repos seem to be using (e.g. "rstats", "r" and "r-package" for R packages, and the different forms of library names for say `magick` which interfaces Image Magick). I am not sure whether topics help SEO, but they sure help browsing e.g. https://github.com/topics/bacterial-database

If you mean auto-generating DESCRIPTION keywords from GitHub repo topics/codemeta.json, we don't have that yet. codemeta.json will contain the repo topics and the keywords from DESCRIPTION (removing duplicates) but things only work in this direction. 

We _could_ add code to generate DESCRIPTION schema.org keywords from GitHub repo topics, but I'm just not sure it'd be useful? Since the only use of DESCRIPTION schema.org keywords is as far as I know to be fed into codemeta.json? I'm happy to have my mind changed though. :wink:

**Comment by katrinleinweber** [comment]
I meant the latter: generating the `X-schema.org-keywords` from GitHub Topics. Because

> GitHub gives you suggestions

and that makes it IMHO the best place to define them manually, but only once :-)

> but I'm just not sure it'd be useful?

Me neither. Presumably, Google can extract the GitHub topics directly. But seeing [all the `X-schema.org` that have been added around here](https://github.com/search?q=org%3Aropensci+schema+filename%3ADESCRIPTION), it surely would be better automatically, than manually, no? Or are those lines part of some cookiecutter/template? I looked through https://github.com/ropensci/dev_guide/search?q=keywords&unscoped_q=keywords.

**Comment by maelle** [comment]
Not sure who added these X-schema.org stuff, was it you @sckott and how did you do that?

**Comment by sckott** [comment]
Carl introduced me to them, so I just kept going with them - @cboettig would know more

**Comment by cboettig** [comment]
Yup, `X-` is CRAN's approved way of adding additional fields that come from approved namespaces, and Kurt approved `X-schema.org` for me in email.  The thought here was that a DESCRIPTION file is still the definitive metadata record for an R package (after all, all R packages must have them!) and so that ideally any metadata would be added and maintained there (after all, `codemetar` is also all about not having to write/edit the `codemeta.json` file manually).  So this approach seemed a good way to add any codemeta fields that didn't already crosswalk into DESCRIPTION in some other way, -- `keywords` is just one example.

**Comment by katrinleinweber** [comment]
So, they were added manually, or copy pasted, but not automatically transferred from some source (file or GitHub topics), correct?

**Comment by cboettig** [comment]
correct, they were added manually to the DESCRIPTION

**Pull request merged**
