### PR TITLE
use commonmark and xml2 for parsing badges cf #179

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by cboettig** [comment]
Cool.  Sorry haven't quite kept up with the thread, but looks like this changes from using a regex pattern to find specific badges, to a more general parsing strategy that can be extended to specific badges, yes?  

It's really nice to see the use of commonmark + xml2 to parse a markdown in a more structured way than regex, and probably makes a ton of sense.  that said, I don't have a good mental picture in this case of precisely what the advantage is; i.e. what things are easier or more accurate to parse this way and why.  Since the badge matching tends to be very manual anyway, it seems like looking for a specific URL match purely in regex is likely to be pretty robust, but maybe not?

**Comment by cboettig** [comment]
p.s. Appveyor not happy?

**Comment by maelle** [comment]
Examples of guesses

https://github.com/ropensci/codemetar/blob/387456e9d62fdb9be936a089d7173e8d21d783b8/R/guess_metadata.R#L76

https://github.com/ropensci/codemetar/blob/387456e9d62fdb9be936a089d7173e8d21d783b8/R/guess_metadata.R#L92

https://github.com/ropensci/codemetar/blob/387456e9d62fdb9be936a089d7173e8d21d783b8/R/guess_metadata.R#L60

I find them more readable because they can be less specific (e.g "project status" would be too little specific)

**Comment by cboettig** [comment]
Thanks.  Yup, happy to merge this since I think this approach is pretty cool.  

Yeah, our current regexs kinda suck, we should probably be searching for very specific patterns like the URLs to those badge services rather than generic terms that could very well appear in other contexts in a README...

**Pull request merged**
