### PR TITLE
add pre-commit hook for DESCRIPTION vs codemeta.json cf #59

### PR DESCRIPTION
**Pull request by maelle**
I haven't added any test because I'm not too sure how to test this 🤔 But I did "test" it on a package of mine and it seemed to work well.

### CODE REVIEW

**Comment by maelle** [comment]
I also don't know what would happen if codemeta.json weren't tracked.

**Comment by maelle** [comment]
cf https://github.com/ropensci/codemetar/issues/59

**Comment by maelle** [comment]
Oh and for now it doesn't look at the README, since I agree that it could become a pain for the developer.

**Comment by cboettig** [comment]
This looks great.

- [ ] I think we should switch the license to GPL if this has GPL'd code.  
- [ ] Can you include in the code comments next to the links that these borrowed functions are GPL'd?  That will be a good note to us to remember why the license is GPL now.
- [ ] pls add yourself as contributor

- [ ] Currently the package uses a couple `devtools` functions since `usethis` was not on CRAN when this was originally released.  (i.e. right above the code where you added the hook).  Can you convert those to `usethis` dependencies so we can drop the `devtools` dependency?  (or we can address that issue later but it should be done before we do a release).

**Pull request merged**
