### PR TITLE
0.1.6 work

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by cboettig** [comment]
👏 Yay, this looks great!  🚀✨

**Comment by cboettig** [comment]
looks like we jus want to rebuild pkgdown site and then we are set for release https://github.com/ropensci/codemetar/milestone/4?  I can probably do that tonight if you give me the all clear

**Comment by maelle** [comment]
If you can solve #109 too then yes! OtherwiseI would solve that issue on Wednesday

**Comment by maelle** [comment]
Btw news is more or less exhaustive but not cran-comments.md, a new copy paste is needed ☺

**Pull request merged**
